### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by jdecool** [boyter/boyter.org#1]
Hi, 

First of all, thanks for your blog, it's very interesting to read your posts.

I've noticed that you change your blog engine. Since that change, your RSS feed has disappeared.

Can add a new one ? RSS is a great tool to be notify of new blog posts.

**Comment by boyter** [comment]
Hah! I never expected anyone to ever raise an issue for this project. Thanks for the kind words.

Ill have a look into how Hugo does RSS feeds.

**Comment by ghost** [comment]
+1 ;)

**Comment by boyter** [comment]
https://boyter.org/index.xml

Its not a full content one like I used to have but I belive most RSS readers download it for you anyway.

**Comment by jdecool** [comment]
Great !

Thanks.

**Comment by boyter** [comment]
No problem at all.
